#아래 적힌 이미지를 베이스 이미지로 한다.
#이 명령어가 실행되면 Dockerhub에서 해당 이미지를 pull한다.
FROM python:3.7
# 환경변수 설정
ENV PYTHONUNBUFFERED 1  
# docker 내에서 /bookiz_ai 라는 이름의 폴더 생성
RUN mkdir /bookiz_ai
# docker 내에서 코드를 실행할 폴더 위치를 /bookiz_ai 로 지정
WORKDIR /bookiz_ai
# 로컬의 requirements.txt 파일을 docker /bookiz_ai/ 폴더로 마운트
ADD ./requirements.txt /bookiz_ai/ 

# docker 내 requirements.txt 파일을 이용하여 패키지 설치
RUN pip install -r requirements.txt 
# 로컬 내 현재 위치에 있는 모든 파일 및 폴더를 docker 의 /bookiz_ai/ 폴더로 마운트
ADD ./ /bookiz_ai/
EXPOSE 8082
CMD ["python", "./manage.py", "runserver", "0.0.0.0:8082"]
